version: '3'
services:
  redis:
    image: "redis:6.2"
    container_name: "dcard-redis"
    ports:
      - "6379:6379"
  api-server:
    build: .
    image: "dcard-demo"
    container_name: "dcard-demo"
    depends_on:
      - "redis"
    ports:
      - "8080:8080"